version: "3.9"
services:
  web:
    build:
      context: .
    volumes:
      - .:/opt/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    user: ${USERID:?err}:${GROUPID:?err}
    working_dir: /opt/app
    ports:
      - '3000:3000'
    command: bash -c "bundle && pwd && foreman start -f Procfile.dev"
    tty: true
    stdin_open: true
    environment:
      - BUNDLE_PATH=vendor/bundle
